# .guthub/ISSUE_TEMPLATE/01-bug_report.yml

name: "🐞 Bug report"
description: Report a problem with vscode-file-header-lite
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the issue.
      placeholder: |
        1. Open a file
        2. Save the file
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should happen?

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happens?

  - type: input
    id: version
    attributes:
      label: Extension version
      placeholder: e.g. 0.0.1
    validations:
      required: true

  - type: input
    id: vscode
    attributes:
      label: VS Code version
      placeholder: e.g. 1.84.0

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g. Windows 11, Ubuntu 22.04
